# This file was auto-generated by scan_baml_colors.py
# Full results saved in scan_results.txt (189KB)

SCAN SUMMARY - Root.exe BAML Color Pattern Analysis
====================================================

BINARY COMPARISON:
  BACKUP:  C:\Users\bash\claude\Root_APP_BACKUP_20260212_172827\Root.exe
  CURRENT: C:\Users\bash\AppData\Local\Root\current\Root.exe
  Size: 616,910,888 bytes each (588.3 MB)
  BACKUP SHA-256:  3735be024dcfa3c778a27961c5433f5b293c900c62cb667fd45c5c7ac71dc007
  CURRENT SHA-256: 67f6d8c8028a53fa876010e75dc7f612b974a9ffe95a25031186720961022c56
  STATUS: *** BINARIES DIFFER - 1,985 bytes changed across 27 regions ***

